name: Publish Site
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install Neocities Gem
        run: gem install neocities
      - name: Create Build
        run: |
          npm i
          npm run build
      - name: Publish Build
        run: NEOCITIES_SITENAME=allmanorofduns NEOCITIES_PASSWORD=$NEOCITIES_PASSWORD neocities push ./build
